# Generated by Django 3.2 on 2021-05-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='projects',
            field=models.ManyToManyField(related_name='categories', to='projects.Project'),
        ),
    ]
