# Generated by Django 3.2 on 2021-05-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(related_name='projects', to='projects.Category'),
        ),
    ]
