language: python
python:
  - 3.8
services:
    - postgresql
install:
    - pip install -r requirements.txt
script:
    - pytest --cov="."
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app:
    master: samueltaiwo