language: python
python:
  - 3.8
services:
    - postgresql
install:
    - pip install -r requirements.txt
before_script:
    - python manage.py migrate
script:
    - pytest --cov="."
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  run: "python manage.py migrate"
  app:
    master: samueltaiwo