language: python
python:
  - 3.8
services:
    - postgresql
before_install:
    - # start your web application and listen on `localhost`
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
    - pip install -r requirements.txt
before_script:
    - python manage.py migrate
    - python manage.py collectstatic --no-input
    - sleep 3 # give xvfb some time to start
    - rackup  # start a Web server
    - sleep 3 # give Web server some time to bind to sockets, etc
script:
    - pytest --cov="."
branches:
  only:
    - master
addons:
  sauce_connect:
    username: "samshultz"
    access_key: "15185d64-b5c8-44cc-afb9-c933dc1115f6"
  chrome: stable
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  run: "python manage.py migrate"
  app:
    master: samueltaiwo