# Generated by Django 3.2 on 2021-05-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_workexperience_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='techstack',
            name='categories',
            field=models.ManyToManyField(to='core.StackCategory'),
        ),
    ]
