# Generated by Django 3.2 on 2021-05-07 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210507_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stackcategory',
            options={'verbose_name': 'stack category', 'verbose_name_plural': 'stack categories'},
        ),
        migrations.RemoveField(
            model_name='techstack',
            name='categories',
        ),
        migrations.AddField(
            model_name='techstack',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stacks', to='core.stackcategory'),
            preserve_default=False,
        ),
    ]
