# Generated by Django 3.2 on 2021-04-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='freelance',
            field=models.CharField(choices=[('available', 'Available'), ('not available', 'Not Available')], default='available', max_length=13),
        ),
    ]
