# Generated by Django 3.2 on 2021-05-05 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about_me', '0002_aboutme_freelance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
