# Generated by Django 3.2 on 2021-05-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0003_alter_aboutme_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
